name: Rebuild docs

# only rebuild docs when there is an update to main
on:
  push:
    branches: [ main ]

jobs:
  rebuild_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build docs
        run: |
          pip install --upgrade pip
          pip install wheel setuptools
          pip install -e . -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-docs.txt
          python scripts/rebuild_docs.py
          mkdocs build
      - name: Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '["docs_src", "docs"]'

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Matbench DocBot

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: ardunn@lbl.gov

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
#          branch: main

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
#          cwd: './path/to/the/repo'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Matbench Docbot: rebuild pages'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
#          pull_strategy: 'NO-PULL or --no-rebase or --no-ff or --rebase'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
#          remove: './dir/old_file.js'

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
#          signoff: true

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
#          tag: 'v1.0.0 --force'


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.


